# Generated by Django 5.0.3 on 2024-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_ordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aberto'), (2, 'Concluído')], default=1, verbose_name='Status'),
        ),
    ]
